BORDER_WIDTH = 2
RECT_SIZE = 50
FIELD_SIZE = 4
WINDOW_WIDTH = RECT_SIZE * FIELD_SIZE + BORDER_WIDTH * 2 + 2
WINDOW_HEIGHT = WINDOW_WIDTH + 200
ROOT_GEOMETRY = f'{WINDOW_WIDTH+10}x{WINDOW_HEIGHT+10}'

BLACK = 'black'
IVORY = 'ivory'
KHAKI = 'khaki1'
TAN_LIGHT = 'tan1'
SLENA = 'sienna1'
LIGHT_ORANGE = 'darkorange'
DARK_ORANGE = 'DarkOrange1'
VERY_DARK_ORANGE = 'DarkOrange3'
VERY_DARK_ORANGE1 = 'DarkOrange4'
BROWN = 'brown'
ORANGE_RED = 'OrangeRed3'
RED = 'Red3'
BLUE = 'skyblue'
BLUE_DEEP = 'blue'

COLORS = {
    2: IVORY ,
    4: KHAKI ,
    8: TAN_LIGHT,
    16: SLENA,
    32: LIGHT_ORANGE , 
    64:  DARK_ORANGE ,
    128: VERY_DARK_ORANGE ,
    256: VERY_DARK_ORANGE1,
    512: BROWN,
    1024: ORANGE_RED,
    2048: RED
    4096: BLUE
    8192: BULE_DEEP
}
